Redis AOF file is corrupted if node fails
defenseunicorns/zarf-package-software-factory pull request #357
Opened 2022-09-10 23:28 UTC by mikevanhemert

Deploy Redis separately in a more robust way so that node failures do not result in data loss.

- Added Redis in Sentinel HA configuration to softwarefactoryaddons.
- Single definition for Redis secret in `kustomizations/bigbang/environment-bb-redis/values.yaml`
- Disabled GitLab Redis
- Configured GitLab to use new Redis Sentinels

2022-09-19 20:03 UTC, mikevanhemert commented
/test all

2022-09-19 20:04 UTC, mikevanhemert commented
/test all

2022-09-19 20:20 UTC, RothAndrew requested changes
Looks good overall, a couple of recommendations, and a few things missing:

* Updated docs, specifically the section that talks about which files to modify and then encrypt using SOPS (in doc/fork-and-build.md)
* Renovate config for auto-PR generation when new tags are released on the Redis chart that we are using.

2022-09-19 20:20 UTC, RothAndrew commented on kustomizations/bigbang/secrets.yaml
> +apiVersion: helm.toolkit.fluxcd.io/v2beta1
Let's move deployment of these secrets into the redis deployment instead of splitting the overall deployment between a separate redis deploy and the big bang deploy

2022-09-19 20:20 UTC, RothAndrew commented on kustomizations/redis/redis/values.yaml
> +    pullPolicy: Always
Could you add resource requests and limits? It's okay if the values are the same as the defaults but having them here will make them much easier to change later when the user goes to deploy it

2022-09-19 20:55 UTC, RothAndrew commented
We should also add to the E2E test. A `kubectl rollout status` will help check for any ImagePullBackOff errors.

2022-09-19 21:33 UTC, RothAndrew commented
@mikevanhemert if you integrate main and rerun the tests you should get past the previous failure

2022-10-25 17:57 UTC, brianrexrode commented
After numerous efforts to incorporate HA Redis with AUTH with no luck, the DI2ME team decided to provide HA Redis without AUTH but with networkPolicies. An ADR (0002-switch-to-authless-ha-redis.md) was created to document this decision as well as future actions.

2022-10-25 17:57 UTC, brianrexrode commented
/test all

2022-10-26 15:03 UTC, runyontr commented
> After numerous efforts to incorporate HA Redis with AUTH with no luck, the DI2ME team decided to provide HA Redis without AUTH but with networkPolicies. An ADR (0002-switch-to-authless-ha-redis.md) was created to document this decision as well as future actions.

Was an issue created upstream on the BigBang repo to track this?

2022-10-26 15:46 UTC, brianrexrode commented
Our plan was to create an issue internally to go back and revisit the issue with AUTH being enabled. I will go ahead and create an issue on the BB repo as well.

2022-10-26 18:02 UTC, brianrexrode commented
/test all

2022-10-26 20:04 UTC, brianrexrode commented on kustomizations/redis/redis/values.yaml
> +    pullPolicy: Always
README was updated to include the decision to forego using AUTH until further investigation or upstream changes can be made.

I will create a new issue to incorporate redis into the the existing renovate config

2022-10-26 20:05 UTC, merged

2022-10-27 14:56 UTC, brianrexrode commented
@runyontr here's a link to the upstream BB [issue](https://repo1.dso.mil/platform-one/big-bang/apps/developer-tools/gitlab/-/issues/159) I just created