Update di2me to bigbang 1.51
defenseunicorns/zarf-package-software-factory pull request #540
Opened 2023-01-26 18:11 UTC by corang

2023-01-26 18:12 UTC, corang commented
/test all

2023-01-26 18:48 UTC, corang commented
/test all

2023-01-27 15:03 UTC, corang commented
/test all

2023-01-27 22:35 UTC, corang commented
/test all

2023-01-30 15:30 UTC, corang commented
/test all

2023-01-30 16:48 UTC, RothAndrew commented
/test all

2023-01-30 16:55 UTC, RothAndrew requested changes

2023-01-30 16:55 UTC, RothAndrew commented on kustomizations/bigbang/common/values-bigbang.yaml
> -              memory: "1Gi"
Can we leave this in and just change the values? It is much easier for end users to be able to configure this when they don't need to go figure out where to put it.

2023-01-30 16:55 UTC, RothAndrew commented on kustomizations/bigbang/common/values-bigbang.yaml
> +
Let's remove this for now rather than leaving it in but commented out. Pull it into a WIP Kyverno  branch if you want it kept

2023-01-30 16:55 UTC, RothAndrew commented on kustomizations/bigbang/common/values-bigbang.yaml
> -        defaultResticPruneFrequency: 168h
Is there a pruneFrequency param for the new NodeAgent stuff?

2023-01-30 16:55 UTC, RothAndrew commented on zarf.yaml
> +      # - https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/kyverno-reporter.git
Same comment as above re Kyverno

2023-01-30 16:55 UTC, RothAndrew commented on zarf.yaml
> +      - https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/neuvector.git
Do we want to remove this for now since Neuvector isn't yet being utilized?

2023-01-30 17:11 UTC, corang commented on kustomizations/bigbang/common/values-bigbang.yaml
> -        defaultResticPruneFrequency: 168h
Not that I can find

2023-01-30 17:18 UTC, corang commented on kustomizations/bigbang/common/values-bigbang.yaml
> -        defaultResticPruneFrequency: 168h
nevermind I found it in their release notes

2023-01-30 17:19 UTC, corang commented on kustomizations/bigbang/common/values-bigbang.yaml
> -              memory: "1Gi"
added back and matched upstream bb values

2023-01-30 17:19 UTC, corang commented on kustomizations/bigbang/common/values-bigbang.yaml
> +
removed

2023-01-30 17:19 UTC, corang commented on kustomizations/bigbang/common/values-bigbang.yaml
> -        defaultResticPruneFrequency: 168h
added the renamed parameter back

2023-01-30 17:20 UTC, corang commented on zarf.yaml
> +      # - https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/kyverno-reporter.git
removed

2023-01-30 17:20 UTC, corang commented on zarf.yaml
> +      - https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/neuvector.git
removed

2023-01-30 17:20 UTC, corang commented
/test all

2023-01-30 17:26 UTC, corang commented
/test all

2023-01-30 19:30 UTC, RothAndrew approved these changes

2023-01-30 19:31 UTC, RothAndrew approved these changes

2023-01-30 19:36 UTC, merged