Change from gatekeeper to kyverno
defenseunicorns/zarf-package-software-factory pull request #548
Opened 2023-01-31 00:48 UTC by corang

2023-01-31 00:48 UTC, corang commented
/test all

2023-02-01 01:36 UTC, corang commented
/test all

2023-02-02 20:20 UTC, corang commented
/test all

2023-02-02 22:22 UTC, corang commented
/test all

2023-02-03 22:17 UTC, corang commented
/test all

2023-02-06 17:10 UTC, corang commented
/test all

2023-02-08 01:32 UTC, corang commented
/test all

2023-02-09 23:54 UTC, RothAndrew requested changes

2023-02-09 23:54 UTC, RothAndrew commented on kustomizations/bigbang/common/values-bigbang.yaml
> +        cpu: "1"
Missing memory request and limit

2023-02-09 23:54 UTC, RothAndrew commented on kustomizations/bigbang/common/values-bigbang.yaml
> +              - "acid*"
Is this needed?

2023-02-10 17:46 UTC, corang commented
/test all

2023-02-10 17:47 UTC, corang commented on kustomizations/bigbang/common/values-bigbang.yaml
> +        cpu: "1"
added

2023-02-10 17:47 UTC, corang commented on kustomizations/bigbang/common/values-bigbang.yaml
> +              - "acid*"
testing without it, I think it is but that was pretty early in playing with kyverno that I added it

2023-02-10 19:13 UTC, corang commented on kustomizations/bigbang/common/values-bigbang.yaml
> +              - "acid*"
Yeah, its not working anymore, I'll dive into exactly why I needed it/why the acid containers are privileged and see if there's a better way

2023-02-15 10:56 UTC, corang commented on kustomizations/bigbang/common/values-bigbang.yaml
> +              - "acid*"
made the exclusion more specific

2023-02-15 10:56 UTC, corang commented
/test all

2023-02-22 23:52 UTC, RothAndrew approved these changes

2023-02-24 19:48 UTC, corang commented
/test all

2023-02-24 20:34 UTC, merged